### PR TITLE
Fix for pbo signing

### PR DESCRIPTION
**Pull request by pixlcrashr**
With this pull request #73 should be fixed.

Moreover, the error was the file name hash, which was wrong because the given files were not sorted (descending).

Although, I added a new unit test with this pull request, to test this kind of behaviour.

### CODE REVIEW

**Comment by pixlcrashr** [comment]
This fix does fix the signature of the `dbo_old_bike` but nevertheless there are files which get signed false.

**Comment by 4d4a5852** [comment]
which files?
and which part of the bisign file - only the 3rd signature (last 128 bytes) or the 2nd one, too?

**Comment by pixlcrashr** [comment]
@4d4a5852 Both signatures. But this problem only happens with this version. `a3lib.py` works perfectly fine after your patch.

I probably implemented this wrong or the whole signing is a bit more complicated in C than I think.

**Comment by pixlcrashr** [comment]
@4d4a5852 I probably found the error: Folders do not get sorted as expected. Probably because of special signs like `/` or `\`.

For example, this is printed out "as ascending sorted list":
```
ace_medical_actions.hpp
test\test.txt
ace_medical_selfactions.hpp
ace_medical_treatments.hpp
ace_settings.hpp
cfgactions.hpp
cfgeden.hpp
cfgeventhandlers.hpp
cfgfactionclasses.hpp
cfgsounds.hpp
cfgvehicles.hpp
cfgweapons.hpp
config.bin
script_component.hpp
stringtable.xml
texheaders.bin
xeh_postinit.sqf
xeh_preinit.sqf
xeh_prep.hpp
xeh_prestart.sqf
```
found the error? The `test/test.txt` part is placed wrong.

Thats just my bad... 🙄
Hopefully the next update is fixing the signing part of armake.

**Comment by pixlcrashr** [comment]
@KoffeinFlummi @4d4a5852 `.pbo`-signing should be fixed by now.

Mod signing was although tested with over 300 different mods.

**Comment by pixlcrashr** [comment]
So, when does this get merged into the main repository? I guess this fix is very import... Its have been now half a year since the last changes on this PR.

**Comment by KoffeinFlummi** [comment]
Merged in 7e70b98e0097f6ddfb7e992e1a46a5a2b5b1f1c5.

Only just now got around to it, sorry. Thanks for the contribution. I replaced your sorting function with `qsort` for performance and simplicity.

**Pull request closed without merging**
